In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import nltk

In [2]:
import sklearn

In [3]:
sklearn.__version__

'1.3.1'

In [4]:
import warnings
warnings.filterwarnings('ignore')

In [5]:
poster = pd.read_csv("tmdb_poster_movie.csv")

In [6]:
poster.head(2)

,title,overview,poster_path
0,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",/3bhkrj58Vtu7enYsRolD1fZdja1.jpg
1,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg

In [7]:
df = pd.read_csv("25k IMDb movie Dataset.csv")
df.head(2)

,movie title,Run Time,Rating,User Rating,Generes,Overview,Plot Kyeword,Director,Top 5 Casts,Writer,year,path
0,Top Gun: Maverick,"$170,000,000 (estimated)",8.6,187K,"['Action', 'Drama']",After more than thirty years of service as one...,"['fighter jet', 'sequel', 'u.s. navy', 'fighte...",Joseph Kosinski,"['Jack Epps Jr.', 'Peter Craig', 'Tom Cruise',...",Jim Cash,-2022,/title/tt1745960/
1,Jurassic World Dominion,2 hours 27 minutes,6,56K,"['Action', 'Adventure', 'Sci-Fi']",Four years after the destruction of Isla Nubla...,"['dinosaur', 'jurassic park', 'tyrannosaurus r...",Colin Trevorrow,"['Colin Trevorrow', 'Derek Connolly', 'Chris P...",Emily Carmichael,-2022,/title/tt8041270/

In [8]:
df.rename(columns={"movie title": "title"}, inplace=True)

In [9]:
df.head(2)

,title,Run Time,Rating,User Rating,Generes,Overview,Plot Kyeword,Director,Top 5 Casts,Writer,year,path
0,Top Gun: Maverick,"$170,000,000 (estimated)",8.6,187K,"['Action', 'Drama']",After more than thirty years of service as one...,"['fighter jet', 'sequel', 'u.s. navy', 'fighte...",Joseph Kosinski,"['Jack Epps Jr.', 'Peter Craig', 'Tom Cruise',...",Jim Cash,-2022,/title/tt1745960/
1,Jurassic World Dominion,2 hours 27 minutes,6,56K,"['Action', 'Adventure', 'Sci-Fi']",Four years after the destruction of Isla Nubla...,"['dinosaur', 'jurassic park', 'tyrannosaurus r...",Colin Trevorrow,"['Colin Trevorrow', 'Derek Connolly', 'Chris P...",Emily Carmichael,-2022,/title/tt8041270/

In [10]:
df = pd.merge(df, poster, on="title", how="inner")

In [11]:
df.head(2)

,title,Run Time,Rating,User Rating,Generes,Overview,Plot Kyeword,Director,Top 5 Casts,Writer,year,path,overview,poster_path
0,Top Gun: Maverick,"$170,000,000 (estimated)",8.6,187K,"['Action', 'Drama']",After more than thirty years of service as one...,"['fighter jet', 'sequel', 'u.s. navy', 'fighte...",Joseph Kosinski,"['Jack Epps Jr.', 'Peter Craig', 'Tom Cruise',...",Jim Cash,-2022,/title/tt1745960/,After more than thirty years of service as one...,/62HCnUTziyWcpDaBO2i1DX17ljH.jpg
1,Jurassic World Dominion,2 hours 27 minutes,6,56K,"['Action', 'Adventure', 'Sci-Fi']",Four years after the destruction of Isla Nubla...,"['dinosaur', 'jurassic park', 'tyrannosaurus r...",Colin Trevorrow,"['Colin Trevorrow', 'Derek Connolly', 'Chris P...",Emily Carmichael,-2022,/title/tt8041270/,"Four years after Isla Nublar was destroyed, di...",/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7460 entries, 0 to 7459
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         7460 non-null   object
 1   Run Time      7460 non-null   object
 2   Rating        7460 non-null   object
 3   User Rating   7460 non-null   object
 4   Generes       7460 non-null   object
 5   Overview      7453 non-null   object
 6   Plot Kyeword  7460 non-null   object
 7   Director      7460 non-null   object
 8   Top 5 Casts   7460 non-null   object
 9   Writer        7460 non-null   object
 10  year          7422 non-null   object
 11  path          7460 non-null   object
 12  overview      7460 non-null   object
 13  poster_path   7460 non-null   object
dtypes: object(14)
memory usage: 816.1+ KB

In [13]:
base_image_url = "https://image.tmdb.org/t/p/"

df["poster"] = df["poster_path"].apply(lambda x: base_image_url + "w500" + x)

In [14]:
df.head(2)

,title,Run Time,Rating,User Rating,Generes,Overview,Plot Kyeword,Director,Top 5 Casts,Writer,year,path,overview,poster_path,poster
0,Top Gun: Maverick,"$170,000,000 (estimated)",8.6,187K,"['Action', 'Drama']",After more than thirty years of service as one...,"['fighter jet', 'sequel', 'u.s. navy', 'fighte...",Joseph Kosinski,"['Jack Epps Jr.', 'Peter Craig', 'Tom Cruise',...",Jim Cash,-2022,/title/tt1745960/,After more than thirty years of service as one...,/62HCnUTziyWcpDaBO2i1DX17ljH.jpg,https://image.tmdb.org/t/p/w500/62HCnUTziyWcpD...
1,Jurassic World Dominion,2 hours 27 minutes,6,56K,"['Action', 'Adventure', 'Sci-Fi']",Four years after the destruction of Isla Nubla...,"['dinosaur', 'jurassic park', 'tyrannosaurus r...",Colin Trevorrow,"['Colin Trevorrow', 'Derek Connolly', 'Chris P...",Emily Carmichael,-2022,/title/tt8041270/,"Four years after Isla Nublar was destroyed, di...",/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg,https://image.tmdb.org/t/p/w500/kAVRgw7GgK1CfY...

In [15]:
df["poster"][20]

'https://image.tmdb.org/t/p/w500/2CQ53CuWD1KdlOkEWhJcEVjqKn4.jpg'

In [16]:
df["id"] = df.index

In [17]:
df.shape

(7460, 16)

In [18]:
df.duplicated(subset="title").sum()

677

In [19]:
df[df["title"]=="The Godfather"]

,title,Run Time,Rating,User Rating,Generes,Overview,Plot Kyeword,Director,Top 5 Casts,Writer,year,path,overview,poster_path,poster,id
2092,The Godfather,"$6,000,000 (estimated)",9.2,1.8M,"['Crime', 'Drama']",The aging patriarch of an organized crime dyna...,"['mafia', 'patriarch', 'crime family', 'organi...",Francis Ford Coppola,"['Francis Ford Coppola', 'Marlon Brando', 'Al ...",Mario Puzo,-1972,/title/tt0068646/,"Spanning the years 1945 to 1955, a chronicle o...",/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7en...,2092

In [20]:
df.isnull().sum()

title            0
Run Time         0
Rating           0
User Rating      0
Generes          0
Overview         7
Plot Kyeword     0
Director         0
Top 5 Casts      0
Writer           0
year            38
path             0
overview         0
poster_path      0
poster           0
id               0
dtype: int64

In [21]:
df["Plot Kyeword"] = df["Plot Kyeword"].apply(lambda x: x.replace(" ", ""))
df["Director"] = df["Director"].apply(lambda x: x.replace(" ", ""))
df["Top 5 Casts"] = df["Top 5 Casts"].apply(lambda x: x.replace(" ", ""))
df["Writer"] = df["Writer"].apply(lambda x: x.replace(" ", ""))

In [22]:
df["Plot Kyeword"]

0       ['fighterjet','sequel','u.s.navy','fighterairc...
1       ['dinosaur','jurassicpark','tyrannosaurusrex',...
2       ['pilot','malecamaraderie','u.s.navy','grumman...
3       ['galaxy','spaceship','robot','rocket','spacea...
4       ['discover','medical','test','reality','fictio...
                              ...
7455    ['scheme','openingnight','accountant','swedish...
7456    ['bankrobber','postamericancivilwar','nudity',...
7457    ['surrealist','blackcomedy','humanmeat','absur...
7458    ['endangeredspecies','fishoutofwater','gangste...
7459    ['mission','gambler','newyorkcity','basedonsta...
Name: Plot Kyeword, Length: 7460, dtype: object

In [23]:
kyewords = df["Generes"] +" "+ df["Overview"] +" " + df["Plot Kyeword"] + " " +df["Top 5 Casts"] + " " + df["Director"] + " " + df["Writer"]

In [24]:
df["kyewords"] = kyewords

In [25]:
df.head(3)

,title,Run Time,Rating,User Rating,Generes,Overview,Plot Kyeword,Director,Top 5 Casts,Writer,year,path,overview,poster_path,poster,id,kyewords
0,Top Gun: Maverick,"$170,000,000 (estimated)",8.6,187K,"['Action', 'Drama']",After more than thirty years of service as one...,"['fighterjet','sequel','u.s.navy','fighterairc...",JosephKosinski,"['JackEppsJr.','PeterCraig','TomCruise','Jenni...",JimCash,-2022,/title/tt1745960/,After more than thirty years of service as one...,/62HCnUTziyWcpDaBO2i1DX17ljH.jpg,https://image.tmdb.org/t/p/w500/62HCnUTziyWcpD...,0,"['Action', 'Drama'] After more than thirty yea..."
1,Jurassic World Dominion,2 hours 27 minutes,6,56K,"['Action', 'Adventure', 'Sci-Fi']",Four years after the destruction of Isla Nubla...,"['dinosaur','jurassicpark','tyrannosaurusrex',...",ColinTrevorrow,"['ColinTrevorrow','DerekConnolly','ChrisPratt'...",EmilyCarmichael,-2022,/title/tt8041270/,"Four years after Isla Nublar was destroyed, di...",/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg,https://image.tmdb.org/t/p/w500/kAVRgw7GgK1CfY...,1,"['Action', 'Adventure', 'Sci-Fi'] Four years a..."
2,Top Gun,"$15,000,000 (estimated)",6.9,380K,"['Action', 'Drama']",As students at the United States Navy's elite ...,"['pilot','malecamaraderie','u.s.navy','grumman...",TonyScott,"['JackEppsJr.','EhudYonay','TomCruise','TimRob...",JimCash,-1986,/title/tt0092099/,For Lieutenant Pete 'Maverick' Mitchell and hi...,/xUuHj3CgmZQ9P2cMaqQs4J0d4Zc.jpg,https://image.tmdb.org/t/p/w500/xUuHj3CgmZQ9P2...,2,"['Action', 'Drama'] As students at the United ..."

In [26]:
df = df[["id", "title", "kyewords", "poster"]]

In [27]:
df.head()

,id,title,kyewords,poster
0,0,Top Gun: Maverick,"['Action', 'Drama'] After more than thirty yea...",https://image.tmdb.org/t/p/w500/62HCnUTziyWcpD...
1,1,Jurassic World Dominion,"['Action', 'Adventure', 'Sci-Fi'] Four years a...",https://image.tmdb.org/t/p/w500/kAVRgw7GgK1CfY...
2,2,Top Gun,"['Action', 'Drama'] As students at the United ...",https://image.tmdb.org/t/p/w500/xUuHj3CgmZQ9P2...
3,3,Lightyear,"['Animation', 'Action', 'Adventure'] While spe...",https://image.tmdb.org/t/p/w500/b9t3w1loraDh7h...
4,4,Spiderhead,"['Action', 'Crime', 'Drama'] In the near futur...",https://image.tmdb.org/t/p/w500/5hTK0J9SGPLSTF...

In [28]:
df["kyewords"][0]

"['Action', 'Drama'] After more than thirty years of service as one of the Navy's top aviators, Pete Mitchell is where he belongs, pushing the envelope as a courageous test pilot and dodging the advancement in rank that would ground ['fighterjet','sequel','u.s.navy','fighteraircraft','pilot','navalaviation','jetfighter','militarypilot','aviation','aircraft'] ['JackEppsJr.','PeterCraig','TomCruise','JenniferConnelly','MilesTeller'] JosephKosinski JimCash"

In [29]:
def remove_noise(text):
    clean_text = re.sub(r'[\d!@#$%^&*()?><:"|;\'.\[\]]', "", str(text))
    clean_text = re.sub(r'[^A-Za-z]+', " ", clean_text)
    return clean_text.lower()

df["kyewords"] = df["kyewords"].apply(remove_noise)

In [30]:
df["kyewords"][0]

'action drama after more than thirty years of service as one of the navys top aviators pete mitchell is where he belongs pushing the envelope as a courageous test pilot and dodging the advancement in rank that would ground fighterjet sequel usnavy fighteraircraft pilot navalaviation jetfighter militarypilot aviation aircraft jackeppsjr petercraig tomcruise jenniferconnelly milesteller josephkosinski jimcash'

In [31]:
nltk.download('stopwords')
from nltk.corpus import stopwords

def remove_stopwords(text):
    return " ".join([i for i in text.split() if i not in stopwords.words("english")])

df["kyewords"] = df["kyewords"].apply(remove_stopwords)

[nltk_data] Downloading package stopwords to /home/shaun/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [38]:
# !python -m spacy download en_core_web_sm

In [39]:
import spacy

nlp = spacy.load("en_core_web_sm")

def word_lem(text):
    doc = nlp(text)
    lemmatized_text = " ".join([i.lemma_ for i in doc])
    return lemmatized_text

df["kyewords"] = df["kyewords"].apply(word_lem)

In [40]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
x = vectorizer.fit_transform(df["kyewords"])

In [41]:
x.shape

(7460, 48030)

In [42]:
from sklearn.metrics.pairwise import cosine_similarity, linear_kernel
similarity = linear_kernel(x)

In [43]:
similarity

array([[1.        , 0.01639972, 0.26794976, ..., 0.        , 0.        ,
        0.        ],
       [0.01639972, 1.        , 0.00243689, ..., 0.        , 0.        ,
        0.        ],
       [0.26794976, 0.00243689, 1.        , ..., 0.        , 0.02125706,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.01671686,
        0.00703756],
       [0.        , 0.        , 0.02125706, ..., 0.01671686, 1.        ,
        0.03614959],
       [0.        , 0.        , 0.        , ..., 0.00703756, 0.03614959,
        1.        ]])

In [44]:
def recommend(movie):
    index = df[df['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(df.iloc[i[0]]["title"])

In [46]:
recommend("Spider-Man")

The Amazing Spider-Man
Spider-Man 2
Spider-Man: No Way Home
Spider-Man: Across the Spider-Verse
Spider-Man 3

In [47]:
import pickle

with open('similer_matrix.pkl', 'wb') as file:
    pickle.dump(similarity, file)

In [ ]:
df.to_pickle("pickle_movie")